"""Add ChatMessage memory fields

Revision ID: 861f99036129
Revises: 959561fdb9ff
Create Date: 2026-06-20 20:32:38.122840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861f99036129'
down_revision = '959561fdb9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('message_role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('message_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_chat_messages_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_user_id', type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('message_content')
        batch_op.drop_column('message_role')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
